# Generated by Django 5.1.7 on 2025-03-19 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgfs', '0002_alter_userprofile_whatsapp_number_savingstransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savingstransaction',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
