# Generated by Django 5.1.7 on 2025-03-22 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgfs', '0003_alter_savingstransaction_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingstransaction',
            name='notes',
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='cumulative_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='end_week',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='is_partial',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='start_week',
            field=models.IntegerField(default=1),
        ),
    ]
