# Generated by Django 5.1.7 on 2025-03-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgfs', '0004_remove_savingstransaction_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingstransaction',
            name='weeks_covered',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_fully_paid_week',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_saved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='savingstransaction',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
