# Generated by Django 5.1.7 on 2025-03-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgfs', '0005_savingstransaction_weeks_covered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingstransaction',
            name='weeks_covered',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_fully_paid_week',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='remaining_balance',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='total_saved',
        ),
        migrations.AlterField(
            model_name='savingstransaction',
            name='amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
