# Generated by Django 5.1.7 on 2025-03-23 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgfs', '0007_weekprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingstransaction',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='savingstransaction',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
