# Generated by Django 5.1.7 on 2025-03-23 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tgfs', '0008_savingstransaction_remaining_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savingstransaction',
            name='end_week',
        ),
        migrations.RemoveField(
            model_name='savingstransaction',
            name='is_partial',
        ),
        migrations.RemoveField(
            model_name='savingstransaction',
            name='start_week',
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='fully_covered_weeks',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='savingstransaction',
            name='next_week',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='WeekProgress',
        ),
    ]
